version: '3'

services:
  drupaldb:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 123456
  mycontent:
    image: drupal
    ports:
      - '8080:80'
    depends_on: 
      - drupaldb
